modified 101-compile

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -3,6 +3,16 @@
 
 # another method
 
-python3 -m compileall $PYFILE
-mv __pycache__/* "${PYFILE}c"
-rm -rf __pycache__
+#python3 -m compileall $PYFILE
+#mv __pycache__/* "${PYFILE}c"
+#rm -rf __pycache__i
+
+if [ -z "$PYFILE" ]; then
+    echo "Error: PYFILE environment variable not set"
+    exit 1
+fi
+
+output_file="${PYFILE}c"
+echo "Compiling $PYFILE ..."
+python3 -m py_compile "$PYFILE" && mv "__pycache__/$PYFILE.cpython-*.pyc" "$output_file" && rm -rf "__pycache__"
+
